#!/bin/bash

SCRIPTDIR=$( (cd -P $(dirname $0) && pwd) )
corename=libra_all
BASEDIR=$SCRIPTDIR/common

# load the shared bash functions log, vlog and Verbose
. $BASEDIR/outputfuncs.bash

verbose=
force=
test=
index=staging:production
while getopts :vfti: opt
 do
      case $opt in
          v) verbose=-v;;
          t) test=-t;;
          f) force=-f;;
          i) index=$OPTARG
      esac
done
shift $((OPTIND-1))

if [ "$force" == "-f" ] ; then
    Verbose "Forcing index rebuild with -f flag"
fi

#if [ "$AWS_ACCESS_KEY_ID" == "" ] ; then
#    Echo "environment variable AWS_ACCESS_KEY_ID must be defined"
#    exit 1
#fi
#if [ "$AWS_SECRET_ACCESS_KEY" == "" ] ; then
#    Echo "environment variable AWS_SECRET_ACCESS_KEY must be defined"
#    exit 1
#fi
#if [ "$AWS_DEFAULT_REGION" == "" ] ; then
#    Echo "environment variable AWS_DEFAULT_REGION must be defined"
#    exit 1
#fi
#if [ "$AWS_REGION" == "" ] ; then
#    Echo "environment variable AWS_REGION must be defined"
#    exit 1
#fi

mkdir -p $SCRIPTDIR/results

Verbose " "
Verbose "Starting update of Virgo4 index for Libra items "`/bin/date "+%Y-%m-%d_%H:%M"`

$SCRIPTDIR/libraetd/index_libraetd  $verbose $test $force -i $index

$SCRIPTDIR/libraoc/index_libraoc  $verbose $test $force -i $index

$SCRIPTDIR/libradspace/index_librads  $verbose $test $force -i $index

$SCRIPTDIR/libradata/index_libradata  $verbose $test $force -i $index

Verbose "Finished update of Virgo4 index for Libra items "`/bin/date "+%Y-%m-%d_%H:%M"`
