#!/bin/bash

SCRIPTDIR=$( (cd -P $(dirname $0) && pwd) )
corename=$( basename $SCRIPTDIR )
DATADIR=${SCRIPTDIR}/data
BASEDIR=$( dirname $SCRIPTDIR )/common
JAVA_MEM="-Xms512M -Xmx512M"

# load the shared bash functions log, vlog and Verbose
. $BASEDIR/outputfuncs.bash

verbose=
force=
test=
index=staging:production
while getopts :vfti: opt
 do
      case $opt in
          v) verbose=-v;;
          t) test=-t;;
          f) force=-f;;
          i) index=$OPTARG
      esac
done
shift $((OPTIND-1))

if [ "$force" == "-f" ] ; then
    Verbose "Forcing index rebuild with -f flag"
fi

#if [ "$AWS_ACCESS_KEY_ID" == "" ] ; then
#    Echo "environment variable AWS_ACCESS_KEY_ID must be defined"
#    exit 1
#fi
#if [ "$AWS_SECRET_ACCESS_KEY" == "" ] ; then
#    Echo "environment variable AWS_SECRET_ACCESS_KEY must be defined"
#    exit 1
#fi
#if [ "$AWS_DEFAULT_REGION" == "" ] ; then
#    Echo "environment variable AWS_DEFAULT_REGION must be defined"
#    exit 1
#fi
#if [ "$AWS_REGION" == "" ] ; then
#    Echo "environment variable AWS_REGION must be defined"
#    exit 1
#fi

query=`cat $SCRIPTDIR/query.txt | sed -e 's/["]/%22/g' -e 's/[*]/%2A/g' -e 's/[[]/%5B/g' -e 's/[]]/%5D/g' -e 's/ /+/g'`
parms='&wt=xml&fl=*'
downloaded=0
let exit_code=0

mkdir -p $DATADIR

diff --normal $SCRIPTDIR/cores_to_process $SCRIPTDIR/cores_to_process 2>&1 > /dev/null
if [[  $? != 0 ]] ; then
    Verbose "Running Busybox, diff is different"
    diff_flag=
else
    Verbose "Not running Busybox, all is well"
    diff_flag=-u
fi

for line in `cat $SCRIPTDIR/cores_to_process`
do
    year=`date "+%Y"`
    solrname=`echo $line| cut -d '|' -f1`
    transform=/LibraOCToWiseMarc.xsl
    libraurlfile=`echo $line| cut -d '|' -f3`
    s3bucket=`echo $line| cut -d '|' -f4 | sed -e "s/2020/$year/"`
    s3deletebucket=`echo $line| cut -d '|' -f5 | sed -e "s/2020/$year/"`
    solrurl=`echo $line | cut -d '|' -f6`
    url=`cat $SCRIPTDIR/$libraurlfile`

    if [[ "$index" =~ $solrname ]]; then
        if [[ $url =~ "private" ]]; then
            hostname=`echo $url | sed -e 's#^[^:]*://##' -e 's#[:/].*$##'`
            ip=`$BASEDIR/resolve_private.bash $hostname`
            LIBRAURL=`cat $SCRIPTDIR/$libraurlfile | sed -e "s#${hostname}#${ip}#"`
        else
            LIBRAURL=$url
        fi
        Verbose "Resolved LibraURL to: $LIBRAURL"

        date=`$SCRIPTDIR/getlastupdatedate $LIBRAURL`
        Verbose "Date of newest item in ${corename} is: $date"

        lastupdate=`cat $DATADIR/lastupdate_$solrname`
        lastupdateNoT=`cat $DATADIR/lastupdate_$solrname | sed -e 's/T/ /'`
        datequeryedited=`date -u -r $SCRIPTDIR/query.txt  "+%Y-%m-%dT%T.0Z"`

        Verbose "Backing up the ${corename} solr record dump from the last update"
        mv $DATADIR/${corename}_${solrname}_data.xml $DATADIR/${corename}_${solrname}_data.xml.bak 2> /dev/null
        numRecordsToReceive=`curl -s "$LIBRAURL?q=$query&rows=0&fl=" | egrep "numFound" | sed -e 's/^.*numFound="//' -e 's/".*$//'`
        Verbose "Querying the ${corename} solr for all ${numRecordsToReceive} records matching the query in the query file"
        numParm="&rows=${numRecordsToReceive}"
        Verbose "Using URL of: $LIBRAURL?q=$query$parms$numParm"
        curl -s "$LIBRAURL?q=$query$parms$numParm" | xmllint --format - | egrep -v "QTime" >  $DATADIR/${corename}_${solrname}_data.xml
        downloaded=1

        cmp $DATADIR/${corename}_${solrname}_data.xml $DATADIR/${corename}_${solrname}_data.xml.bak
        cmpresult=$?
        numReceived=`cat $DATADIR/${corename}_${solrname}_data.xml | egrep "<doc>" | wc -l`
        if [[ "$numRecordsToReceive" != "$numReceived" ]] ; then
            Echo "Error: requested $numRecordsToReceive, but received $numReceived"
            let exit_code=1
        else
            Verbose "Received $numReceived records -- as requested"
        fi

        datescriptedited=`date -u -r $SCRIPTDIR/$transform  "+%Y-%m-%dT%T.0Z"`
        datelasttransform=`date -u -r $DATADIR/virgo4_${corename}_${solrname}.xml  "+%Y-%m-%dT%T.0Z"`
        datelastdownload=`cat $DATADIR/lastupdate_${solrname}`
        Verbose "Storing last download date"
        echo `date -u -r "$DATADIR/${corename}_${solrname}_data.xml" "+%Y-%m-%dT%T.0Z"` > $DATADIR/lastupdate_wise_${solrname}

        if [[ "$force" == "-f" ]]; then
            Verbose "Forcing $solrname index rebuild with -f flag"
        else
            Verbose "Checking whether $corename needs reindexing in $solrname index"
            if [[ "$cmpresult" != "0" ]] ; then
                Verbose "Records downloaded from $corename different from last time they were downloaded"
            fi
            if [[ "$datescriptedited" > "$datelasttransform" ]] ; then
                Verbose "LibraToWiseMarc transform for the $solrname index is newer than last update: $datescriptedited > $datelasttransform "
            fi
        fi

        newdata=0
        if [[ "$cmpresult" != "0" || "$datescriptedited" > "$datelasttransform" || "$force" == "-f" ]]
        then
            Verbose "Backing up the virgo/solr add document from the last update for $solrname index"
            mv $DATADIR/LibraOCtoWiseMarcOutput.xml $DATADIR/LibraOCtoWiseMarcOutput.xml.bak  2> /dev/null

            Verbose "Transforming the libra/solr record dump into a new MARCXML set for UVA Wise"
            avalon_url_filename=$( dirname $SCRIPTDIR )/avalon/avalonprod_solr_url.txt
            avalon_url_private=`cat $avalon_url_filename`
            if [[ $avalon_url_private =~ "private" ]]; then
                hostname=`echo $avalon_url_private | sed -e 's#^[^:]*://##' -e 's#[:/].*$##'`
                ip=`$BASEDIR/resolve_private.bash $hostname`
                avalonsolrurl=`cat $avalon_url_filename | sed -e "s#${hostname}#${ip}#"`
            else
                avalonsolrurl=$avalon_url_private
            fi
            Verbose "Resolved AvalonSolrURL to: $avalonsolrurl"
 

            java ${JAVA_MEM} -jar $BASEDIR/saxon9.jar  $DATADIR/${corename}_${solrname}_data.xml  $SCRIPTDIR/$transform avalonSolrUrlBase="$avalonsolrurl" |
                 sed -e 's/\\n/\&#10;/g' > $DATADIR/LibraOCtoWiseMarcOutput.xml 2>&1 | vlog
            cmp -s $DATADIR/LibraOCtoWiseMarcOutput.xml $DATADIR/LibraOCtoWiseMarcOutput.xml.bak 2> /dev/null
            newdata=$?
        fi
        if [[ "$newdata" != "0" ]]; then
            Verbose "Generate Binary Marc Records from MARCXML"
            $BASEDIR/to_utf8 < $DATADIR/LibraOCtoWiseMarcOutput.xml > $DATADIR/LibraOCtoWiseMarcOutput.mrc
            #Verbose "Upload transformed records to ${solrname} S3 bucket"
            #if [ "$test" == "-t" ]; then
                #Echo "aws s3 cp $DATADIR/virgo4_${corename}_${solrname}.xml ${s3bucket}/virgo4_${corename}_${solrname}.xml"
            #else
                #Echo "aws s3 cp $DATADIR/virgo4_${corename}_${solrname}.xml ${s3bucket}/virgo4_${corename}_${solrname}.xml
            #fi
        fi
    fi
done
    
if [[ "$exit_code" != "0" ]]; then
    Echo "Didn't receive all of the records, returning an error code"
fi
Verbose "Done updating core $corename"
exit $exit_code
