#!/bin/bash

#talks to the solr search engine of libra (at ir.lib.virginia.edu) to find the date of the most recent update
SCRIPTDIR=$( (cd -P $(dirname $0) && pwd) )
corename=$( basename $SCRIPTDIR )
DATADIR=${SCRIPTDIR}/data
BASEDIR=$( dirname $SCRIPTDIR )/common

LIBRAURL=$1
if [[ "$LIBRAURL" == "" ]] ; then
    exit 1
fi
#url encode the querystring from the file data/query.txt
query=`cat $SCRIPTDIR/query.txt | sed -e 's/["]/%22/g' -e 's/[*]/%2A/g' -e 's/[[]/%5B/g' -e 's/[]]/%5D/g' -e 's/ /+/g'`
getDate='&rows=1&fl=timestamp&sort=timestamp+desc'

curl -s "$LIBRAURL?q=$query$getDate" | xmllint --format - | egrep '<date' | sed -e 's/^.*<date[^>]*>//' -e 's:</date>::'
