#! /bin/bash
# to_utf8.sh
# Diagnostic program to display marc records.
# $Id: to_utf8.sh 

E_BADARGS=65

BASEBINDIR=$( (cd -P $(dirname $0) && pwd) )
marc4j_jar_name=`ls -t $BASEBINDIR  | egrep "^marc4j" | egrep "[.]jar$" | head -1`
marc4j_jar="$BASEBINDIR/$marc4j_jar_name"

java -jar $marc4j_jar to_utf8 $* 

exit 0


